// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace BeeronomicsMVC.Models
{
    public partial class BeeronomicsDBContext : DbContext
    {
        public BeeronomicsDBContext()
        {
        }

        public BeeronomicsDBContext(DbContextOptions<BeeronomicsDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Drink> Drink { get; set; }
        public virtual DbSet<DrinkPrices> DrinkPrices { get; set; }
        public virtual DbSet<PurchaseHistory> PurchaseHistory { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Drink>(entity =>
            {
                entity.Property(e => e.AddedBy).HasMaxLength(55);

                entity.Property(e => e.Category).HasMaxLength(55);

                entity.Property(e => e.DateAdded).HasColumnType("datetime");

                entity.Property(e => e.DateUpdated).HasColumnType("datetime");

                entity.Property(e => e.Name).HasMaxLength(255);

                entity.Property(e => e.PriceLastIncreased)
                    .IsRequired()
                    .HasDefaultValueSql("('1')");

                entity.Property(e => e.Symbol).HasMaxLength(10);

                entity.Property(e => e.UpdatedBy).HasMaxLength(55);
            });

            modelBuilder.Entity<DrinkPrices>(entity =>
            {
                entity.HasKey(e => e.Pk_DrinkPrice_ID)
                    .HasName("PK__DrinkPri__F36E9BA6C6111D71");

                entity.HasIndex(e => e.Fk_Drink_ID, "UQ__DrinkPri__0EE79BE54C45F354")
                    .IsUnique();

                entity.Property(e => e.Pk_DrinkPrice_ID).ValueGeneratedNever();

                entity.Property(e => e.ActivePrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.MaxPrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.MinPrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

                entity.HasOne(d => d.Fk_Drink)
                    .WithOne(p => p.DrinkPrices)
                    .HasForeignKey<DrinkPrices>(d => d.Fk_Drink_ID)
                    .HasConstraintName("FK__DrinkPric__Fk_Dr__3A81B327");
            });

            modelBuilder.Entity<PurchaseHistory>(entity =>
            {
                entity.HasKey(e => e.Pk_Purchase_ID)
                    .HasName("PK__Purchase__E8B165581CA51FEF");

                entity.Property(e => e.ActivePrice).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.Purchases).HasDefaultValueSql("((0))");

                entity.Property(e => e.TimeStamp).HasColumnType("datetime");

                entity.HasOne(d => d.Fk_Drink)
                    .WithMany(p => p.PurchaseHistory)
                    .HasForeignKey(d => d.Fk_Drink_ID)
                    .HasConstraintName("FK__PurchaseH__Fk_Dr__35BCFE0A");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}