// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BeeronomicsMVC.Models
{
    public partial class Drink
    {
        public Drink()
        {
            PurchaseHistory = new HashSet<PurchaseHistory>();
        }

        public int ID { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string AddedBy { get; set; }
        public DateTime? DateAdded { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? DateUpdated { get; set; }
        public bool Active { get; set; }
        public string Photo { get; set; }
        public bool PriceLastIncreased { get; set; }

        public virtual DrinkPrices DrinkPrices { get; set; }
        public virtual ICollection<PurchaseHistory> PurchaseHistory { get; set; }
    }
}