// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeeronomicsMVC.Models
{
    public partial class DrinkPrices
    {
        public int Pk_DrinkPrice_ID { get; set; }
        public int? Fk_Drink_ID { get; set; }
        public decimal? ActivePrice { get; set; }
        public decimal? MinPrice { get; set; }
        public decimal? MaxPrice { get; set; }
        public DateTime? UpdatedOn { get; set; }

        public virtual Drink Fk_Drink { get; set; }
    }
}