// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeeronomicsMVC.Models
{
    public partial class PurchaseHistory
    {
        public int Pk_Purchase_ID { get; set; }
        public int? Fk_Drink_ID { get; set; }
        public int? Purchases { get; set; }
        public decimal? ActivePrice { get; set; }
        public DateTime? TimeStamp { get; set; }

        public virtual Drink Fk_Drink { get; set; }
    }
}